COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure
  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:123456@localhost:3306/test?charset=utf8mb4'
  SQLALCHEMY_TRACK_MODIFICATIONS: False

  # 日志文件存放位置
  LOGGING_PATH: ./logs
  LOGGING_LEVEL: 'INFO'

  # redis配置
  REDIS_EXPIRE: 60*60
  REDIS_HOST: 172.16.0.150
  REDIS_PORT: 30960
  REDIS_USER: ""
  REDIS_PASS: "redispasswd"
  REDIS_DB: 9

  # celery 配置
  USE_CELERY: False
  CELERY_ACKS_LATE: True
  CELERYD_PREFETCH_MULTIPLIER: 1
  BROKER_URL: "redis://:redispasswd@172.16.0.150:30960/6"
  CELERY_RESULT_BACKEND: "redis://:redispasswd@172.16.0.150:30960/7"
  CELERY_TASK_SERIALIZER: 'msgpack'
  CELERY_RESULT_SERIALIZER: 'json'
  CELERY_TASK_RESULT_EXPIRES: 36000
  CELERY_ACCEPT_CONTENT: ['json', 'msgpack']

  # 是否开启定时任务,默认不开启
  SCHEDULER_OPEN: False

  # 定时任务配置
  SCHEDULER_API_ENABLED: True
  JOBS:
    - id: my_job
      func: app.task.task:my_job
      trigger: interval
      seconds: 60
    - id: db_query
      func: app.task.task:db_query
      trigger: cron
      hour: 14
      minute: 47

  TMP_DIR: ./tmp


DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  REDIS_HOST: flask_redis